name: Vanilla Desktop
id: vanilla-ci-building
vibversion: 1.0.7

stages:
- id: build
  base: ghcr.io/vanilla-os/core:dev
  singlelayer: false
  labels:
    maintainer: JustSaft
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"' > /etc/environment
    - sed -i '4,10d' /etc/profile
    - apt update
    - apt upgrade -y
    - apt clean
    - apt-mark hold snapd gnome-software-plugin-snap
    - apt -y install squashfs-tools minisign

  - name: vanilla-tools
    type: shell
    source:
      type: tar
      url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.0/vanilla-tools.tar.gz
      checksum: 0e1d92d9c9154f9a115e97b40ff692afa52ddd0d9f770a8ec67440bf1a48aa72
    commands:
    - mkdir -p /usr/bin
    - cp /sources/vanilla-tools/vanilla-tools/lpkg /usr/bin/lpkg
    - cp /sources/vanilla-tools/vanilla-tools/cur-gpu /usr/bin/cur-gpu
    - chmod +x /usr/bin/lpkg
    - chmod +x /usr/bin/cur-gpu

  - name: apx-vso-pico-shutdown-service
    type: shell
    commands:
    - mkdir -p /etc/systemd/user/graphical-session.target.wants/
    - ln -s /etc/systemd/user/apx-vso-pico.service /etc/systemd/user/graphical-session.target.wants/

  - name: includes
    type: includes
    includes:
      - kdeconnect-deps.yml

  - name: cleanup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - lpkg --lock

  - name: sysconf-setup
    type: shell
    commands:
      - rsync -a /etc/ /sysconf/

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard
          - rm -f ./minisign.pub ./minisign.key
          - chmod +x /usr/share/init.d/010-fsguard.sh

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*